package com.datalogic.decode.configuration;

/**
 * The <code>CameraWedgeBarcodePosition</code> is an enumeration defining the position
 * of the barcode generated by the camera wedge.
 */
public enum CameraWedgeBarcodePosition {
	/**
	 * The barcode is always centered inside the frame.
	 */
	CENTERED,
	/**
	 * The barcode is positioned depending on the specified X and Y coordinates.
	 */
	CUSTOM;
}
