package com.datalogic.decode.configuration;

/**
 * The <code>CameraWedgeBarcodeOrientation</code> is an enumeration defining the orientation
 * of the barcode generated by the camera wedge.
 */
public enum CameraWedgeBarcodeOrientation {
	/**
	 * The barcode orientation depends on the device current rotation.
	 */
	AUTO,
	/**
	 * The barcode is always in portrait orientation.
	 */
	PORTRAIT,
	/**
	 * The barcode is always in landscape orientation.
	 */
	LANDSCAPE;
}
